spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_TEST_DATABASE_HOST}:${MYSQL_TEST_DATABASE_PORT}/${MYSQL_TEST_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_TEST_USERNAME}
    password: ${MYSQL_TEST_PASSWORD}
---
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true

---
---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
