spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_TEST_DATABASE_HOST}:${MYSQL_TEST_DATABASE_PORT}/${MYSQL_TEST_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_TEST_USERNAME}
    password: ${MYSQL_TEST_PASSWORD}
    hikari:
      maximum-pool-size=100
---
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

---
spring:
  batch:
    jdbc:
      initialize-schema: always
---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
---
fcm:
  service-account-file: ${FIREBASE_KEY_PATH}
  project-id: ${FIREBASE_PROJECT_ID}

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE

